name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Configure Docker to use the gcloud CLI
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t europe-west1-docker.pkg.dev/cs1-mzn-12345/frontend-repo/vite-frontend:latest .

    - name: Push Docker image
      run: |
        docker push europe-west1-docker.pkg.dev/cs1-mzn-12345/frontend-repo/vite-frontend:latest
